### ISSUE TITLE
FSK Runner: log autogenerated simulation script

### ISSUE THREAD

**Issue by mfilter** [SiLeBAT/FSK-Lab#134]
For transparency reasons it is necessary to provide the simulation script generated by the FSK Runner node on the basis of the simulation settings to the user - ideally in the FSK object.

**Comment by miguelalba** [comment]
I do not understand the issue. The runner node is evaluating the parameter values from the selected evaluation and then executes the model and visualization scripts. No simulation script is generated in the runner node but in the writer node that stores all the simulations into SED-ML.

I could plot all the R code evaluated in the runner node as part of the output port object. In this case I would advise to output this code in a separated port like a table since the other nodes will not need it.

**Comment by mfilter** [comment]
The question is the translation from Sed-ML (generated in the FSK Simulation Configurator) into R code or Matlab code or Pyhton code in the FSK Runner before execution of the model script. How ever you do the "evaluation of parameter values" this has to be made transparent, so that one can check if the "evaluation commands" are correct.

**Comment by miguelalba** [comment]
The FSK Simulation Configurator node is not creating actual SED-ML but simple data structures keeping the paramater values which are later stored in SED-ML by the writer node.

I could either,
a) replace the current visualization of the parameters with SED-ML in the view of the output port. It would be similar to the static view of the R scripts.
b) output SED-ML in a second port object. The easiest approach would be a 1x1 table with an XML cell like in the PMM-Lab tables.

**Comment by mfilter** [comment]
Today we agreed, that the FSK Writer takes responsibility for this, i.e. the FSK Writer writes out in addition to the SED-ML files appropriate script files that can be used by 3rd parties to reproduce the simulation results.

**Comment by miguelalba** [comment]
Since https://github.com/SiLeBAT/FSK-Lab/commit/dd7507254ece47580ed206a1d3d3eab5c884062c the output port (FskPortObject) and the runner node dialog now show the parameters script to be generated from each simulation. These scripts are not stored yet in the files.

**Comment by miguelalba** [comment]
As discussed I need to wait for the proposal of mandatory parameter values to be accepted. Only then we could replace the default parameters script with the generated "parameters scripts" out of the simulations of each model. Otherwise I would need to introduce yet another RDF annotation to separate the deprecated parameter script with the new generated scripts.

**Comment by schuelet** [comment]
@mfilter I think this one can go. The simulation scripts are provides under /simulations. Any objections?

**Comment by mfilter** [comment]
OK.
