### ISSUE TITLE
FSK editor legacy

### ISSUE THREAD

**Issue by OctavioMV** [SiLeBAT/FSK-Lab#147]
It can not be opened if a FSK creator is not connected to it

**Comment by miguelalba** [comment]
The legacy editor node does not have the same feature from the new editor that allows to enter a model from the input. Instead it only takes an input model from the input port which is mandatory. It could be discussed to add this feature but I believe the legacy and deprecated nodes are supposed to remain unchanged.

**Comment by mfilter** [comment]
I agree, we should leave legacy nodes as they are. 
Question to @miguelalba : 
Can we just update the node description accordingly?
Can we add other even older versions of the legacy node that still work with the files from the model repository? (Just in case this would solve the problem)

**Comment by miguelalba** [comment]
Yes, it is a good idea to update the node's description. But I do not advice to create yet another version of the legacy node since we already have three versions of the nodes (RAKIP, deprecated and legacy) and the development effort will increase noticeably. I could instead try to fix and support old files.
