### ISSUE TITLE
FSK to metadata 

### ISSUE THREAD

**Issue by ahmadswaid** [SiLeBAT/FSK-Lab#150]
The JSON generated out of this node contains some keys which contain space character Like:
General Information instead of generalInformation.

**Comment by miguelalba** [comment]
Currently the FSK to metadata node is generating the keys,
* `General information`
* `Scope`
* `Data background`
* `Model math`

Would you need camel case names for the four columns like?
* `generalInformation`
* `scope`
* `dataBackground`
* `modelMath`

**Comment by miguelalba** [comment]
@TarGue are you affected by this node? Are you using it in a critical workflow or any Generic Javascript view you may use now in the server?

**Comment by miguelalba** [comment]
I committed the changes into a separated branch `fsk2metadata` and the commit is 0a34ff460ec6f763aee11560ca6e3c484a157ada. Please check it so that I can merge it into the master branch.

**Comment by TarGue** [comment]
@miguelalba as I know you had already camelCase names in the JSON to metdata and not the other way around. 
In the end if you want to extract keys and generate automatically the coloumn or row names ist the first option much better. For sure will this change effect our Node and maybe also @ahmadswaid  work, but there I'm not sure.

**Comment by TarGue** [comment]
@miguelalba You know that I'm able to read? 
See below the current structure, what the Node is generating. If I'm not fully blind and stupid it's using camelCase letters or do you see something different? So it will not effect the Version, but If you want to change it to the other format, I'm in and take care on it. As I said in my post before it makes more sense. In that case I have to change the code. 

``
{
         "generalInformation":{
         "name" : "Duarte_FittingDistributionToMicrobialCounts",
         "source" : "",
         "identifier" : "Duarte.R",
         "creators" : [ ],
         "creationDate" : 1478646000000,
         "modificationDate" : [ 1478646000000, 1478646000000 ],
         "rights" : "Public",
         "isAvailable" : true,
         "url" : "http://bfr.bund.de",
         "format" : "",
         "reference" : [ ],
         "language" : "",
         "software" : "R",
         "languageWrittenIn" : "",
         "modelCategory" : {
           "modelClass" : "",
           "modelSubClass" : [ ],
           "modelClassComment" : "",
           "basicProcess" : [ ]
         },
         "status" : "",
         "objective" : "",
         "description" : ""
         
},

**Comment by miguelalba** [comment]
Taras what I understood from Ahmad is that you are converting the column names so that they use camel case. The FSK2Metadata node is not producing column names with white spaces. As you can check in Fsk2MetadataNodeModel the columns for "General information", "Model math" and "Data background" are including white spaces.

@Override
  protected PortObjectSpec[] configure(PortObjectSpec[] inSpecs) throws InvalidSettingsException {

    // Column specs
    final DataColumnSpec generalInformationSpec =
        new DataColumnSpecCreator("General information", JSONCell.TYPE).createSpec();
    final DataColumnSpec scopeSpec = new DataColumnSpecCreator("Scope", JSONCell.TYPE).createSpec();
    final DataColumnSpec dataBackgroundSpec =
        new DataColumnSpecCreator("Data background", JSONCell.TYPE).createSpec();
    final DataColumnSpec modelMathSpec =
        new DataColumnSpecCreator("Model math", JSONCell.TYPE).createSpec();

    // table spec
    final DataTableSpecCreator tableSpec = new DataTableSpecCreator()
        .addColumns(generalInformationSpec, scopeSpec, dataBackgroundSpec, modelMathSpec);
    return new DataTableSpec[] {tableSpec.createSpec()};
  }

  @Override
  protected DataTableSpec[] configure(DataTableSpec[] inSpecs) throws InvalidSettingsException {

    // Column specs
    final DataColumnSpec generalInformationSpec =
        new DataColumnSpecCreator("General information", JSONCell.TYPE).createSpec();
    final DataColumnSpec scopeSpec = new DataColumnSpecCreator("Scope", JSONCell.TYPE).createSpec();
    final DataColumnSpec dataBackgroundSpec =
        new DataColumnSpecCreator("Data background", JSONCell.TYPE).createSpec();
    final DataColumnSpec modelMathSpec =
        new DataColumnSpecCreator("Model math", JSONCell.TYPE).createSpec();

    // table spec
    final DataTableSpecCreator tableSpec = new DataTableSpecCreator()
        .addColumns(generalInformationSpec, scopeSpec, dataBackgroundSpec, modelMathSpec);
    return new DataTableSpec[] {tableSpec.createSpec()};
}

IIRC this was problem for Ahmad since he needed camelcase names with no white spaces to match the names of the classes to deserialize JSON (not sure of this). I do not care about the contents of the cell, that is, the contents of the top level components: General information, scope, data background and model math. They are created by the Jackson object mapper and thus they have proper names.

Finally I am merging the branch and closing this issue. I do not think it is going anywhere. Should you or Ahmad have more problems, please just open another one.
