### ISSUE TITLE
loading time of FSK workflow

### ISSUE THREAD

**Issue by OctavioMV** [SiLeBAT/FSK-Lab#153]
The loading time of one FSK workflow in knime is much longer than another with knime nodes.

**Comment by mfilter** [comment]
Hi @miguelalba , could you have a look at that?

**Comment by OctavioMV** [comment]
@miguelalba, I wrote this message because I realized that a workflow with less than 100 FSK nodes needs around the same time than my Gropin Knime workflow which contains thousands of Knime nodes. I can send you both workflows on Monday you to see the differences.

**Comment by miguelalba** [comment]
@mfilter No, I have not yet looked into but I know the problem.

@OctavioMV The data holder used in most FSK-Lab nodes (FskPortObject) is not as optimized or mature as the KNIME table. Besides, it also has the overhead of handling resources and the libraries.

1. To load extra resources like CSV or RData files the nodes are deep copying the files. I should improving this by keeping only the path to the resource. Fortunately, I think you are not using resources.

2. Models with libraries require the workflow to download and install the libraries before loading the workflow. In addition, since the library registry is a shared resource, the rest of the nodes need to wait to the current node using the registry to finish since the access is exclusive. The access to the libraries registry needs to be exclusive as otherwise we could run into models trying to install the same library more than once. This is a tricky problem and will take time.

### Regarding the libraries
 i. One solution is to install lazily the libraries when used. The workflows would load fast but the overhead of downloading and installing the libraries would rest on the runner node whose running time would increase dramatically.
ii. Another approach is to actually download and install the libraries in the background. The required libraries could be ordered to be installed to a separate thread running in the background that would take care of the libraries quietly. The challenge here would be to control the access to the registry and making sure that all the libraries are installed before executing a runner node. A potential error with this approach is the runner node executing before the libraries are installed, thus I would need to check the thread and wait for it before executing the runner. The upsides are a fast load of the workflows and hopefully a faster execution of the runner node than in _i_ as the user may wait some time to run the latter node.

**Comment by schuelet** [comment]
Apparently, the implemented solution was to use lazy loading. I don't think that workflows with FSK-Lab nodes load particularily fast, but libraries are only installed when the Runner needs them.
Resources are also not loaded directly anymore, but handled by using paths.

Closing this then.
