### ISSUE TITLE
FSK Creator: mountpoint-relative path does not work for Metadata spreadsheet

### ISSUE THREAD

**Issue by mfilter** [SiLeBAT/FSK-Lab#158]
The node will issue: 
ERROR FSK Creator          0:19       Execute failed: ("NullPointerException"): null

**Comment by miguelalba** [comment]
I reproduced the error in the attached workflow. Notice that the full path needs to be changed to your PC.
[Spreadsheet_paths.knwf.zip](https://github.com/SiLeBAT/FSK-Lab/files/2047849/Spreadsheet_paths.knwf.zip)

**Comment by miguelalba** [comment]
The creator node was already supportive both mountpoint-relative paths and absolute URLs but sometimes writing the URLs can be tricky since they cannot include literals like whitespaces. For the example for the earlier WF (now updated) whitespaces need to be replaced with `%20` and hashtags with `%23`.

[Spreadsheet_paths.knwf.zip](https://github.com/SiLeBAT/FSK-Lab/files/2048744/Spreadsheet_paths.knwf.zip)
