### ISSUE TITLE
FSK Runner does node find additional file if a JS FSK Simulator is used before.

### ISSUE THREAD

**Issue by llavall** [SiLeBAT/FSK-Lab#163]
please refer to workflow sent via mail.

**Comment by miguelalba** [comment]
[mail from Lars]
the Runner fails because the path of the new working directory file is not forwarded through it. I think you did not update your node yet to support the new feature. Could you do that please?

[Original workflow from Lars](https://github.com/SiLeBAT/FSK-Lab/files/2047459/Ahmad_issue.knwf.zip)

**Comment by miguelalba** [comment]
Original issue #162 is closed.

**Comment by miguelalba** [comment]
@llavall and @ahmadswaid I created a test workflow running a simple model using a working directory. This model runs:
1. After creation. Creator > Runner
2. After JS Editor. Creator > Editor > Runner
3. After JS Simulator. Creator > Simulator > Runner
4. After JS Editor and simulator. Creator > Editor > Simulator > Runner. This last case is the closest to your workflow.

Could you both please import the workflow and execute all the nodes? Thanks,

Miguel

**Comment by llavall** [comment]
I did uninstall it again and installed again and now it seems to work

**Comment by miguelalba** [comment]
Ok. So if Ahmad verifies it we can close this ticket.

**Comment by miguelalba** [comment]
Ahmad told me it works for him.
