### ISSUE TITLE
Add README in archive

### ISSUE THREAD

**Issue by miguelalba** [SiLeBAT/FSK-Lab#175]
Add a README into archive on model execution:
* How to execute model from R
* How to execute model from FSK-Lab

**Comment by mfilter** [comment]
Thanks for creating this ticket.
Just an addition: the Readme should also include a link to the installation page of FSK-Lab and some guidance (or even a simple workflow inside the archive) on how to get the model running inside FSK-Lab or inside R. Here an toy example for a PMM-Lab model:

“The model is made available in the PMF-ML format, i.e. as .pmfx file. To execute the model or to perform model-based predictions it is recommended to use the software PMM-Lab. PMM-Lab is an open-source extension of the open-source data analytics platform KNIME. To install PMM-Lab follow the installation instructions available at: https://foodrisklabs.bfr.bund.de/pmm-lab_de/ 
Once PMM-Lab is installed a new KNIME workflow should be created and the PMFX Reader node should be dragged into it. This “PMF Reader” node can be configured to read in this .pmfx file. To perform a model-based prediction connect the Out-Port of the “PMF Reader” node with the “Predictor View” and use the node specific configuration user interface (GUI) to select the desired input parameters, e.g. Temperature. Results of model-based predictions are given instantly in the nodes GUI while changing the input parameters. After closing the node’s GUI and execution of the “Predictor View” node the prediction results are also available at the out port as XML object in the column “Data”.”

**Comment by miguelalba** [comment]
Hi Matthias,

from what I understood of this issue from Tasja #183 the readme files were to be provided by the users and imported in FSK-Lab with the creator node. Your issue though seems to indicate that a README should be generated automatically by the nodes which conflicts with #183.

If we were to provide a generic README how would we proceed when the user imports a handwritten README? Should we take the one provided by the user?

From your suggestion I understand we should provide a different README for each model according to the tool used to create it: PMM-Lab or FSK-Lab.

Finally, if I remember correctly PMM-Lab models are not supported yet in FSK-Lab. But we can still work on a generic README for it.

HTH,
Miguel

**Comment by llavall** [comment]
We already have the option to allow the modeler to include a Readme.txt. 

In addition to that, we need to implement a FSK generated Readme.txt, providing some information about FSKlab. 

But instead of having two files, we want them to be combined:
If a FSKX file is written it needs to be checked if there already is a Readme.txt present: 

1. If it is present the writer will add the text from the FSK Readme.txt to the top. This process is repeated if the model is written again.

2. If it is not present the writer provides a Readme.txt. 

We need to provide a meaningful text and to clarify what information should be provided

**Comment by mfilter** [comment]
A suggestion for a auto-generated Readme.txt file for **PMM-Lab** is the following:

"The model is made available in the PMF-ML format, i.e. as .pmfx file. To execute the model or to perform model-based predictions it is recommended to use the software PMM-Lab. PMM-Lab is an open-source extension of the open-source data analytics platform KNIME. To install PMM-Lab follow the installation instructions available at: https://foodrisklabs.bfr.bund.de/pmm-lab_de 
Once PMM-Lab is installed a new KNIME workflow should be created and the “PMF Reader” node should be dragged into it. This “PMF Reader” node can be configured to read in the given “.pmfx” file. To perform a model-based prediction connect the out-port of the “PMF Reader” node with the “Predictor View” and use the node specific configuration user interface (GUI) to select the desired simulation parameters, e.g. temperature. Results of model-based predictions are given instantly in the nodes GUI while changing the input parameters. After closing the node’s GUI and execution of the node the prediction results are also available at the out-port as XML object in the column “Data”.”"

A suggestion for  an auto-generated Readme.txt file for **FSK-Lab** could be the following:

"This model is made available in the FSK-ML format, i.e. as .fskx file. To execute the model or to perform model-based predictions it is recommended to use the software FSK-Lab. FSK-Lab is an open-source extension of the open-source data analytics platform KNIME. To install FSK-Lab follow the installation instructions available at: https://foodrisklabs.bfr.bund.de/fsk-lab_de/ 
Once FSK-Lab is installed a new KNIME workflow should be created and the “FSKX Reader” node should be dragged into it. This “FSKX Reader” node can be configured to read in the given “.fskx” file. To perform a model-based prediction connect the out-port of the “FSKX Reader” node with the “FSK Simulation Configurator JS” node to adjust if necessary input parameters and store this into a user defined simulation setting, After that connect the output port with the input of a FSK Runner node that perform the simulation and look at the results at the node's outport."

Just as a first suggestion. Any comment or improvement is welcome.

**Comment by miguelalba** [comment]
@llavall I disagree. I would rather not combine readmes. It is unnecessary complex and weird things could occur. Like importing a model previously run in FSK-Lab would unnecessarily add again the README again and again. I would suggest instead to only include the readme provided by Matthias if the readme was not provided by the user.

@mfilter In the case of PMM-Lab is much easier as the user there cannot import a README. Therefore a generated readme would always be added by the writer node. I am creating a ticket for the PMM-Lab case.

If both of you agree, I can implement it and close the issue.

**Comment by llavall** [comment]
@miguelalba  that was the idea from Matthias - maybe you talk back to him. You should make sure that the users Readme is there and ours - since they will differ.

**Comment by mfilter** [comment]
I'm fine with the procedure for PMM-Lab.

Re FSK-Lab:
I agree with Lars that what he described has been discussed and agreed. However the point on complexity is valid as well. The rational for having also the "default" FSK-Lab Readme text on top of the users text is, that the user's Readme might contain information on the model, not on FSK-Lab. The information on FSK-Lab is however important, so that people know what to do with this file.
So my suggestion as a solution:
We have just one Readme.txt file in the FSKX file
This file contains always the FSK-Lab Readme default text wrapped inside ##FSK-Lab version xyz##   .... ##/FSK-Lab##
(or a similar pair of tags). 
If the user has provided own Readme files or a Readme text this follow below that.
The Writer node checks if the pair of tags is already present, if yes no new FSK-Lab Readme text is included, if no this will be added before the users text.

@miguelalba : would that solve the issues raised by you?
