### ISSUE TITLE
Very long loading time when opening FSK-Lab workflows in KNIME using https://silebat.bintray.com/lars2/

### ISSUE THREAD

**Issue by tasjabfr** [SiLeBAT/FSK-Lab#181]
We experience extremely long loading times when we try to open workflows in KNIME that have previously been executed with the newest build of FSK-Lab (https://silebat.bintray.com/lars2/). 

We are not sure what this is related to, but when the workflow is loading the message always refers to the port of each node (see image). 

![loading_workflow](https://user-images.githubusercontent.com/37534054/41596115-cc55309c-73b8-11e8-852d-4d5d336e9a43.PNG)

**Comment by miguelalba** [comment]
Workflows with models using R packages take a long time to load due to downloading and installing packages. Is it also taking long to load workflows already opened or are you opening the workflows after restarting KNIME? Every time KNIME is closed the libraries are deleted, so it is expected to download and install the libraries again. It could also be that I made an error an the same libraries are downloaded every time a workflow is opened during the same execution of KNIME (without a restart). Although IIRC I did not experience this last week.

I created the ticket #177 last week to delegate the installation of packages to the runner so WFs load fast but still the installation overload would go to the runner.

**Comment by tasjabfr** [comment]
I just checked and it only takes this long after I restart KNIME. I alos checked the time to load and it took 6 minutes. Do you think it would be possible to omptimize this? I am restarting KNIME quite often after updating the drop folders in the workflows.

**Comment by miguelalba** [comment]
You do not need to restart KNIME to see the changes in the drop folders, closing and reopening the workflows is enough and does not flush the libraries.

Yesterday I implemented the changes described in #177 to only install libraries in the runner. If you want I could release a test build with that change so your workflows load faster.

The only optimisation I can think of is to skip the installation of base R packages that are included in the base installation of R. miniCRAN is downloading all the dependencies of each R package. Nevertheless, it could be that the user removes a base R package and then we would miss it?

**Comment by mfilter** [comment]
I think we need to find in the mid-term a more generic solution for this problem. Maybe we have to explore deeper into the Docker concept, so that every FSKX file comes with it's docker container that make sure everything is there for execution. For sure there are issues with that as well.
