### ISSUE TITLE
Possibility to include readme.txt-file during model creation and export to FSKX

### ISSUE THREAD

**Issue by tasjabfr** [SiLeBAT/FSK-Lab#183]
We would like to be able to include a readme.txt file during model creation and export to FSKX. 

I am aware that we can already upload text files through the "Creator" node, but I could imagine that it would be very useful if we could have an extra field in the Creator node (dark blue in picture below), where the user can provide the readme file. It would then be important that the readme-file is automatically be written into the FSKX file (given that a readme-files was provided).

![unbenannt](https://user-images.githubusercontent.com/37534054/41716971-ba0f69ee-7547-11e8-8789-c90eef2323ce.PNG)

I addition, it would be helpful for the user if this readme.txt was visible in the FSK object and the Editor, just like e.g. the visualization script. 

Thanks a lot!
Tasja

**Comment by miguelalba** [comment]
There is already a opened ticket for this #175. I guess we could leave #175 opened for the contents of the README and this one for the actual support and implementation.

The changes to the interface are trivial. Regarding the extension of the file, I would rather use a .README extension to distinguish from other plain text. Otherwise we could run into issues with multiple plain text files in a model.

Could you provide me with example files to create a model including the README?

By the way, another possibility is to support markdown, producing richer documentation. But it would take me longer to update the interface, since markdown would need to be converted to HTML.

**Comment by tasjabfr** [comment]
Sorry, I should have checked the open tikcets first. 

I have attached the Norvirus dose response model with a readme.txt that was originally provided with the model when we received it form the FDA. 

HTH,
Tasja
[model files.zip](https://github.com/SiLeBAT/FSK-Lab/files/2124094/model.files.zip)

**Comment by miguelalba** [comment]
Implemented, neet to make a build though.

![creator_readme](https://user-images.githubusercontent.com/19906968/41786192-c025788c-763c-11e8-8b69-6bf0615737fd.png)
![view_readme](https://user-images.githubusercontent.com/19906968/41786194-c06c912c-763c-11e8-8430-e17c2ebc87aa.png)
