### ISSUE TITLE
more then one set of fsklab files in knime plugins folder

### ISSUE THREAD

**Issue by llavall** [SiLeBAT/FSK-Lab#207]
I recently discovered, that in all my KNIME installation I had 2 sets of FSKlab files. I assume this is part of the installation/update issues we face. I attach one example from my mac with 2 versions from the same day.
![screen shot 2018-07-30 at 14 42 20](https://user-images.githubusercontent.com/25248947/43402476-1d18d5fe-9413-11e8-9c66-2488b9ea4c82.png)
It might help to find the issue.

Best wishes 
Lars

**Comment by miguelalba** [comment]
I ask KNIME last week and they are to answer this week. I reproduced it with PMM-Lab too.

**Comment by miguelalba** [comment]
It is normal in Eclipse. Nevertheless plugins wrapping Java libraries which does not change since they do not have code and always keep the same jar should have a fixed version, without the `.qualifier` suffix. Otherwise we would keep many copies of the same Java libraries. It makes sense though to keep old versions of original plugins like ours which do involve code that is changing.
