### ISSUE TITLE
where to publish a new build

### ISSUE THREAD

**Issue by llavall** [SiLeBAT/FSK-Lab#213]
In the future, I would like to make more use of the test-update site and the KNIME test server we have. The idea is to create a new build for FSK-lab and publish it via https://dl.bintray.com/silebat/fsklab_test/ only. I am going to set up the KNIME test server to use this update site instead of icpmf. We can then test on this server and as soon as we are sure everything is working well the same build is uploaded to https://dl.bintray.com/silebat/fsklab_icpmf, where the external server is receiving the build from.

Best wishes
Lars

**Comment by mfilter** [comment]
Very good.

**Comment by miguelalba** [comment]
Currently only the releases are deployed to the ICPMF update site aka "stable" update site. If you want I could configure the build so that all the other commits are deployed to the test update site.

The shortcoming I see is that the lifespan of the test builds will be very short as they may be replaced by another commit in a few minutes.
