### ISSUE TITLE
PMM Lab errors after FSK-Lab installed

### ISSUE THREAD

**Issue by schuelet** [SiLeBAT/FSK-Lab#216]
Pmm Lab features like Writer and Reader Nodes don't work (Execute failed: 'org/apache/commons/lang3/StringUtils'). This error occurs when FSK Lab is also installed in Knime.

**Comment by mfilter** [comment]
In my case (workflow attached) I get the following errors for the different PMFX or PMF Writer nodes:
ERROR PMFX Writer (deprecated) 0:267      Execute failed: ("CombineArchiveException"): null
ERROR PMFX Writer (deprecated) 0:268      Execute failed: Tertiary Model_HuNoV.pmfx could not be opened
ERROR PMF Writer           0:275      Execute failed: Tertiary Model_HuNoV.pmfx could not be opened

However the PMF Reader works
[TestWF.zip](https://github.com/SiLeBAT/FSK-Lab/files/2289707/TestWF.zip)

**Comment by schuelet** [comment]
I only get "org/apache/commons/lang3/StringUtils" error messages. 
[PMM-Error.zip](https://github.com/SiLeBAT/FSK-Lab/files/2289734/PMM-Error.zip)

**Comment by ahmadswaid** [comment]
I have noticed the following in the workflow of Matthias
- log10 count (without parentheses around the count word)  is being used as a unit of parameter D of the Primary Models_HuNoV_TV_MNV part which the first example in this workflow.
- but the PMMLAB database doesn't contain this unit with parentheses around the count word like this (  log10 (count)  ).
changing the database to have this unit or changing the unit in the creator to one of the units defined in the database make things good.
@mfilter: if you see it's necessary, I can dig more into the problem to see why the database doesn't contain this unit in that form.


@schuelet please poll the changes to get rid of (apache commons lang 3) error since it's solution is committed by @miguelalba in his last commit on PMMLAB.

**Comment by mfilter** [comment]
Dear Ahmad,

thanks for looking into it. The unit issue explains the problem. This is an intrinsic problem with PMM-Lab, as the local DB is not available if you share a workflow (as has been done in this case).
So I will create an independent ticket for this problem.

**Comment by miguelalba** [comment]
Hi Thomas,

the error you mentioned earlier comes from the de.bund.bfr.formats project that is duplicated in PMM-Lab and FSK-Lab.  When both are installed this project is overwritten.

Unfortunately this project is missing a dependency that is included later in the FSK nodes project (Apache commons Lang) so the FSK nodes work. But this project is unexpectedly used by PMM-Lab nodes which are not defining this dependency and thus fail.

I fixed it in the last build but did not include in the code repository since we had errors. I just included the dependency explicitly in the project in FSK-Lab. But this is just a workaround. A more robust solution would be to rename both projects in PMM-Lab and FSK-Lab do that they are not overwritten.

In the meantime you could add the dependency in the plugin.xml of the BfR formats project in FSK and include it in separate branch as a pull request so I could review it if you have doubts.

Lots of thanks and sorry for typos. I am writing from my phone,
Miguel
