### ISSUE TITLE
The repository view node has issues to show the table on smaller screens.

### ISSUE THREAD

**Issue by llavall** [SiLeBAT/FSK-Lab#217]
I think I can enable the scroll function, but maybe there is more work needed or we decide to ignore smaller screens :-)

**Comment by miguelalba** [comment]
Do you mean the model repository created with the Generic JavaScript View of @ahmadswaid and @TarGue? If so, that node is using an embedded script. That script is saved in the workflow and we do not have any JS node in FSK-Lab so I cannot do much about it. I cannot even fix it with an FSK-Lab release since it is outside, so I do not see the point of creating the ticket here.

I would advise instead to either create a repository with this views and report there any issues with it or use the discussions I opened in the organization account at https://github.com/orgs/SiLeBAT/teams/fg41.

**Comment by llavall** [comment]
Ja, thats what I mean and I know you are not involved in it @miguel  . As you see you are not even assigned to this task, therefore, I see no point of you taking care of it - just leave it to them. THX

**Comment by llavall** [comment]
by the way, we have in the meantime established the internal gitlab for workflow related stuff. Would be great if we all could get an account there and use it for workflow related tickets in the future.

**Comment by TarGue** [comment]
With the next Update of the code, we will apply completely Bootstrap which will take care on a responsive consistent design. 
In the long-term I thought on a solution, where we generate small table-cards for each row, on mobile or small screen.
