### ISSUE TITLE
different runner behaviour if simulation JS node was used

### ISSUE THREAD

**Issue by llavall** [SiLeBAT/FSK-Lab#222]
Octavio has found the issue, that a model runs in the runner, but not if a simulationJS node was used beforehand. We should somehow make sure that the behaviour is the same with and without:

@Miguel. Please check the code "if("car" %in%in% rownames(installed.packages())) == FALSE)
{install.packages("car"); require(car)} else{require(car)}". 

It is a part of the VIZ_DR model code (this will not probably be the lattest problem of this model but if we clarify why it gives this error and look for a solution we can go forward. Can it be a problem with the libraries? In this case we could include this function in the list of avoidable functions in fsk. After commenting these two lines from the code I get the following error "Error: expr # 34 "dataEllipse(bootparms_bp[, 1], bootparms_bp[, 1], bootparms_bp[, 3], levels = 0.9, center.pch = 0, col = "red", lwd = 2, lty = 1, plot.points = F, add = T)": could not find function "dataEllipse" " Could it also be from library topic?

Attached the file VIZ_DR.fskx (The zip is only written - remove it to use the file

[VIZ__DR.fskx.zip](https://github.com/SiLeBAT/FSK-Lab/files/2302579/VIZ__DR.fskx.zip)

**Comment by llavall** [comment]
I also updated the Upload workflow: Now the simulation node is used for testing the model as well and the error message ist shown directly.

**Comment by ahmadswaid** [comment]
The Simulation Configuration uses the model metadata (which is provided inside any  .fskx file) as a reference to check the type of the parameter if it's of type INPUT or CONSTANT in order to remove the output parameter from the list of parameters in the simulation.

This metaData.json doesn't contain the model math part. so this FSKObject has no parameters definition to be referenced in the simulation configuration.

I don't know how this file has simulation file inside, but no model math definition, since fsklab Creator generates the default simulation from the model math(which is missing in this case).
