### ISSUE TITLE
Please provide me a workflow which updates bintray

### ISSUE THREAD

**Issue by llavall** [SiLeBAT/FSK-Lab#268]
The workflow should be able to:

1. Upload the exact same version of the build which is currently in testing via: `https://dl.bintray.com/silebat/fsklab_test/` 
to the production sites:
`https://dl.bintray.com/silebat/fsklab_icpmf/ `
`https://dl.bintray.com/silebat/fsklab/`
`https://dl.bintray.com/silebat/pmmlab/`
`https://dl.bintray.com/silebat/pmmlab_icpmf/`
`...?`

2. Save that very same version of the build as one knime installation file inside the lokal workspace e.g. knime://knime.mountpoint/builds/

**Comment by miguelalba** [comment]
I believe this is related to your idea of deploying update sites through a KNIME workflow.

Like I said many times, please do not write unrelated issues to FSK-Lab here. Unrelated issues include spreadsheets hosted outside of the FSK-Lab repo like Google Sheets, JavaScript views embedded into workflows and not contained in the repo. For non-related issues GitHub discussions or mails are better suited. Otherwise we end up with a highly polluted issue tracker and developers wasting time.

**Comment by llavall** [comment]
As we want to shift all topics which are not related to the KNIME nodes to our GITLAB server, I created a ticket there: http://gitlab.bfr.bund.de/knime_workflows/Bintray/issues/1
