### ISSUE TITLE
Refactor ReaderNodeModel.reset()

### ISSUE THREAD

**Issue by miguelalba** [SiLeBAT/FSK-Lab#273]
The implementation of the ReaderNodeModel.reset() can be improved.

Firstly, there is no a single comment and this is a complicate chunk dealing with working directories.

## First three lines
In the first three lines there are three potential null pointer exceptions. *getContext*, *getWorkflowManager* and *getContext* may return null and none of the cases is checked. Also, I ignore what should happen if *null* is returned here.

```java
NodeContext nodeContext = NodeContext.getContext();
WorkflowManager wfm = nodeContext.getWorkflowManager();
WorkflowContext workflowContext = wfm.getContext();
```

## Java stream
In the Java stream there another two unchecked null pointer exceptions (*getCurrentLocation* and *getNodeContainer*).
```java
      Files.walk(workflowContext.getCurrentLocation().toPath())
          .filter(path -> path.toString()
              .contains(nodeContext.getNodeContainer().getNameWithID().toString()
                  .replaceAll("\\W", "").replace(" ", "") + "_" + "workingDirectory"))
          .sorted(Comparator.reverseOrder()).map(Path::toFile).forEach(File::delete);
```

- This stream is too complicated and Java streams are harder to debug than regular for loops.
- If I understand correctly you want to remove all the files with a trailing "_workingDirectory". You could just use the [String.endsWith method](https://docs.oracle.com/javase/7/docs/api/java/lang/String.html#endsWith(java.lang.String)).
- The Java stream is wrapped in a try-cath catching IOExceptions but this does not protect against the two NullPointerExceptions.

**Comment by ahmadswaid** [comment]
- First, the workflowContext will never be null since it represents the workflow and if it does not exist then the node which is calling it will not exist and there is no need to check the NullPointerException.

- Second, the code which is written in the walk method is meant not only to find and delete all the folders which end with "workingDirectory" token but also to check that they are related to current node in the mean that we are not deleting folders which are representing the working directory of other reader nodes which maybe exist in the same workflow.

**Comment by mfilter** [comment]
@ahmadswaid : could you please add this information to the code and then close the ticket? In case you have any idea for additional tests that could be integrated into our automated test pipeline, please add that as well. Thx

**Comment by miguelalba** [comment]
There are no commits since October 17th. Please push them and then close the issue. I would like to see them.
