### ISSUE TITLE
Simulation setting is not used anymore in the runner

### ISSUE THREAD

**Issue by llavall** [SiLeBAT/FSK-Lab#313]
Unfortunately, the selected simulation in the simulation setting node is not considered anymore in the runner. 
For the webportal this is a big problem, since it is the only way the user can select which simlulation setting should be run.

1. Please configurate the runner node to respect the incoming selection. But make sure, that a new selection in the runner must overwrite that selection for this model (same for flowvariable). I don't know how to assure that the modeler always knows which selection is used (runner or simulation setting node). Maybe we should remove the option from the runner and keep it as variable?

2. I would like to receive the simulation settings as a useful outport. A simple solution could be to forward the selected simulation as flowvariable. An extensive version would be a table at the outport.

**Comment by miguelalba** [comment]
1. has been fixed in the commit fb58203. This ticket contains a bugfix (1) and a new feature (2). For this and future tickets I would suggest to only place one bug or feature per ticket so we can close them quickly.

@llavall, for this reason, I will close this ticket and you can open another one for 2 where we can gather requirements.
