### ISSUE TITLE
Editor JS: remove access rights 

### ISSUE THREAD

**Issue by schuelet** [SiLeBAT/FSK-Lab#346]
In the node settings: access rights (checkbox for readable,writable) should be removed to avoid confusion since they are not changeable here (ref. Esther 1.)

> 1.	I cannot change the access rights (the ticks): 

![image](https://user-images.githubusercontent.com/19906968/63432458-7a84d000-c421-11e9-9132-b5e3e981ab47.png)

**Comment by miguelalba** [comment]
The GUI element (JTable) is created automatically for the data given. Here since readable and writable are booleans, Swing is creating checkboxes automatically for them. A simple solution is to replace these booleans with strings like Yes or No so that Swing will not create checkboxes and confuse our users.
