### ISSUE TITLE
Editor JS: model metainformation from drop-down list is not correctly displayed for existing models

### ISSUE THREAD

**Issue by schuelet** [SiLeBAT/FSK-Lab#357]
General >Model Category>Model Class list in drop down menu is incomplete

> 3.	By the way the Model Class select list does not display all the model categories. 
![image](https://user-images.githubusercontent.com/19906968/63438257-4b279080-c42c-11e9-9922-f785593f6d4e.png)

**Comment by mfilter** [comment]
The original issue is probably solved, but the Editor node dose not display the correct information for model class when it is linked to an existing model. At least not for the model class, where the first entry of the drop-down list is displayed instead of the correct value. See 
knime://BfR-extern/FSKX_Testing/FSK-Lab_2.0/broken_workflows/testCampy  
General information -> Model caegory -> Model class: here "[Data]" is shown, but it should be "Dose-response model".
I think this is related with similar observations in other tickets.
