### ISSUE TITLE
Editor JS: order of parameter fields makes no sense

### ISSUE THREAD

**Issue by schuelet** [SiLeBAT/FSK-Lab#362]
Model Math> Parameter> name should be at the top (or the beginning) of the list (ref. Esti 7.)

> 7.	I also find it strange that the name of the parameter is not presented at the beginning of the table, is it not so easy to find. 

![image](https://user-images.githubusercontent.com/19906968/64954343-95622d00-d885-11e9-8150-0617fbca47d2.png)

**Comment by miguelalba** [comment]
The order of the fields is lost when generating the JSON Forms from the yaml definitions.

```java 
JSONObject jObject = new JSONObject(contents).getJSONObject("definitions");
```

When the JSONObject *definitions* is returned the fields of every definition is in order since the underlying objects are maps. To keep the order of the properties the swagger definition should be used directly instead of converted to JSON since the properties are in order in the YAML.

See: https://github.com/SiLeBAT/EmfFormsGenerator/blob/master/src/main/java/de/bund/bfr/knime/fsklab/nodeengine/java2node/Swagger2JSONFormsBridge.java
