### ISSUE TITLE
Wrong tooltips of spatial and temporal information (editor)

### ISSUE THREAD

**Issue by miguelalba** [SiLeBAT/FSK-Lab#408]
The tooltips of temporal and spatial information in editor are mixed. Temporal information has the tooltip of spacial information and the latter has no tooltip.
![image](https://user-images.githubusercontent.com/19906968/79471944-88681080-8003-11ea-9823-6a03184893c5.png)

**Comment by schuelet** [comment]
No tooltips since UI update. Infos missing. @miguelalba Are the descriptions of the metadata fields in the Editor also controlled by a service or app? There are a lot of fields without a description.

![image.png](https://images.zenhubusercontent.com/5e4ba30f8f780f7f48f8f306/d95c4d7e-19de-47e9-92e1-1bb57328b88f)

**Comment by schuelet** [comment]
fixed in https://github.com/SiLeBAT/FSK-Lab/pull/851
