### ISSUE TITLE
Runner node should stop at the first error

### ISSUE THREAD

**Issue by miguelalba** [SiLeBAT/FSK-Lab#523]
The FSK-Lab Runner node runs each line of the R code separately. If in one line an error or warning occurs this has no effect, i.e. this is not communicated to the end-user. This has multiple consequences the stopifnot-command is not working, which in my opinion is an important command to ensure that the model runs correctly. Also, the node shows green lights as long as the plot is successfully created. If the plot was successful but there is an error in R the user will not be informed. I agree this should not happen but I might unintentionally during the model development. 

My wish: 
1) I would like to be informed that something went wrong and I would like to know if it is an R or a FSK-Lab node related problem. Of cause getting details about the issue would be nice, but the information that there is a problem with R or KNIME is already very helpful. 
2) I would like to be informed, e.g. On the "Write good R code for FSK-Lab"-web page about the way how the node runs the R code.

**Comment by mfilter** [comment]
please update this ticket

**Comment by schuelet** [comment]
While the model script is still fully executed, even if there was a problem along the way, the node now checks for errors after each R execution (run model script, run visualization script ect.). The error is catched and converted to a custom Exception which gives a clearer indication of what went wrong. And because of this custom exception, the node fails as expected.
It isn't perfect and there may be a few things missing, but it is in the spirit of what this ticket was about.
