### ISSUE TITLE
changelog not updated anymore?

### ISSUE THREAD

**Issue by llavall** [SiLeBAT/FSK-Lab#870]
I still refer to https://github.com/SiLeBAT/FSK-Lab/blob/master/features/de.bund.bfr.knime.fsklab.feature/CHANGELOG.md but there hasn't been any change for fsk for a while. Is it just not updated anymore or did it move to another URL due to the 2.0 version?

**Comment by schuelet** [comment]
@miguelalba if you have some time, could you take care of that please?

**Comment by miguelalba** [comment]
We have not updated in a while. I can look in the log and write here a proposal for a list of changes. I would need @schuelet and @ahmadswaid to review it if I miss something.

**Comment by schuelet** [comment]
@miguelalba I worked it over. Can you add this to the official changelog for FSK-Lab 2.0, please.
We have not updated in a while. I can look in the log and write here a proposal for a list of changes. I would need @schuelet and @ahmadswaid to review it if I miss something.

# Changed
- raised version number to FSK-Lab 2.0
- support of older FSK-Lab nodes in form of deprecated nodes
- minimum version of supported KNIME: 4.0 (#671)
- new hosting site: BfR Gitlab https://gitlab.bfr.berlin/silebat
- new KNIME update site (p2): BfR Gitlab https://gitlab.bfr.berlin/silebat/repositories/raw/master/fsklab/
- FSK-Joiner node now allows for a maximum of 4 models to be joined at once
- FSK-Joiner now allows joining of models written in different script lanugages https://github.com/RakipInitiative/ModelRepository/issues/14
- FSK-Runner now creates a flow-variable to link to the files generated by the model execution
- FSK-Runner now optionally creates a JSON file containing flattened data (and metadata) of all parameters used by the model
- FSK-Runner now opens plot when "execute with open view" is selected
- FSK-Runner now provides a default plot image if the model doesn't contain a visualization script
- FSK-Editor now automatically creates a UUID for the model-id (identifier)
- FSK-Editor now allows adding Output parameters without removing the simulations of a model
- FSK-Simulation Configurator node now supports save as default
- FSK-Simulation Configurator contains a description field
- FSK-Reader: if a model is downloaded from a URL, creates a flow variable containing its local path
- Support for excel files (xlsx)
- Extract embedded vocabularies project to a separate library https://github.com/SiLeBAT/FSK-Lab/commit/8063dd3811667c2829d6f09a250b245b7e6d79a5

- Remove old unused resources https://github.com/SiLeBAT/FSK-Lab/commit/4523d36252df6fe6bf2b251b864cf613f679543d

- Load controlled vocabularies straight from bundle (no copy in the middle)


# Added
- UI overhaul of all nodes using JavaScript views https://github.com/SiLeBAT/FSK-Lab/issues/508
- new node: FSK DB View, which allows to view and download the models in the online repository ("landingpage-app" service by BfR)
- new feature Join Component: FSK DB View, Editor and Joiner subscribe to each other, allowing to locally join and download models hosted on BfR
- more meaningful error messages appear in Console if model execution fails https://github.com/SiLeBAT/FSK-Lab/issues/328
- added support for knime protocol paths in manager classes https://github.com/SiLeBAT/FSK-Lab/commit/bb95a2cc5a139e48a60dbf0b8ebe88827942841a
- Add a long-text type in UI schema and create textareas for these props. https://github.com/SiLeBAT/FSK-Lab/commit/d37199c421aac4e09552b2b640018f73aa7ed10d
- Add endpoint for converting metadata (empty) (#641)
- correct main python interpreter is taken from model metadata  https://github.com/RakipInitiative/ModelRepository/issues/112
- Export the JS View Table as BufferedDataTable with the selection (#691)
- Joiner reordering, tooltip on parameters ports mouseover https://github.com/SiLeBAT/FSK-Lab/commit/c48adab59d65eb3814e332e2e4ea230dd5b794de
- Joiner Reorder useCurrentValueAsDefault MouseoverTooltip Java Part https://github.com/SiLeBAT/FSK-Lab/commit/69de417dec2d518fa1e4447f1146a0fe5360edb1
- Metadata conversion and joining algorithms




# Fixed
- add .fskx extention to file in writer if it is not given by the user (#695)
- escape HTML special Chars 
- fixed a bug where min/maxValue of parameters would brick slider #874
- relaxed constraint of file parameters being accessible after execution #872
- add global validation message area #869
- rewrote the way, parameters are stored to avoid reordering issue #868
- fix classification issue in interactive mode / adapt Ajv to KnimeServer #864
- fix: editor doesn't enable editing newly added rows in any table 
- Writer bug joined models different languages #862 
- individual scriptHandlers for sub-models in Writer #861
- Continuous delivery of JSON schema From model.yaml(SPOT) #857
- Editor bug picking a model from configuration dropdown menu fails node #856
- fix Joiner bug if modelName ends with space character #855
- support "joining" of models without opening the view #854
- Sets identifier in initializeModel #853
- Fixes plot file extension #852
- Fix tooltips issues from #408 #851
- Change parameter value tooltip (#487) #850 
- Editor validation #849 
- update selected value #843 
- Use ScriptHandler with try-with-resource #841
- added a check for null value for reading date objects #836
- removed hard validation for email in editor #835 
- Update vocabularies 2.0.1 #834 
- add a path to flowvariable of Reader if model is downloaded #833
- store R JSON data in file to deal with large file data 
- fixed bug where row selection doesn't work if DBview uses input table #830
- fix a bug in editing reference dialog #829
- Editor bug reference hotfix #828
- fix missing description of fields #827
- fix a bug in saving panel with ArrayForm #826
- fix bug that prevents editing existing references #822
- Fsk editor js UI is not working for long drop down list #821
- redirect exception message to super constructor to preserve message #818
- parameter classification is converted to uppercase. #817
- fix bug in loading the code mirror instance in server mode 
- fix shared setting between FSKDB view nodes #811
- fix https://github.com/RakipInitiative/ModelRepository/issues/283 #810
- updated the endpoints from /backend to /landingpage #809
- Outdated default endpoints #808
- model delivery bug to the joiner in Component mode #807
- fix https://github.com/RakipInitiative/ModelRepository/issues/276 #804
- fixing simulation scenarios generation #803
- Error msg failed save output parameter #802
- throwing custom errors in scriptHandler saveGeneratedResources #801
- add exception if model script fails in scriptHandler runSnippet() #800
- PackageNotFoundException for jsonHandler importLibraries #799
- Editor bug: combined model outport broken #796
- created some custom exceptions to help throw more useful messages #794
- removed rounding of double parameters to allow more precision #793 
- fixed bug where setting the path to .fsk folder is sometimes skipped #792
- fix simulations deletion in the Editor #791 
- added some custom exceptions that log appropriate error messages #790
- fix outport bug after reloading the joiner component #789
- Fskdb view model re selection after saving #788
- fix https://github.com/RakipInitiative/ModelRepository/issues/261 #787
- fixed bug where files from other models would not get found 
- Joiner bug: model with "" in title can't be rendered in Joiner bug #320
- Model Bug: PiresOutbLA2011-Salmonella wrong parameter value bug #319 
- Joiner bug: error on opening view if modelName ends with space character bug #315 
- FSKDBview Bug: scripts not shown properly bug #313
- Joiner bug: svg not valid in KNIME report #309
- Editor bug: switching model category in JS view does not change the View High prio #305
- Editor bug: picking a model from configuration dropdown menu fails node High prio #304 
- editor bug: creation date starts at 0 bug #301
- Runner Bug: Rserve doesn't end after Runner completes execution. High prio bug
- Component bug: no valid outportObject bug #297
- editor bug: cant edit more than one item in a list bug #296
- editor bug: cant save a product bug #295
- editor bug: author email always not valid bug #294
- editor Classification enum bug: editing parameter without touching classification concatenates enum bug #290
- Editor vocabularies bug: wrong vocabularies for parameter #289 
- Editor vocabularies bug: language_written_in missing #288
- Component bug: changes made in codemirror tabs are not saved #287
- Component bug: repository url in DB View is shared on KNIME startup #284 
- Component bug: editing multiple models breaks Joiner View #283
- Joiner Bug: some parameters in simulations have null value #275
- Joiner bug: possible simulations not added #274
- scriptHandler bug: R path to user libraries are removed #270
- Component reloading outport issue #268
- simulator bugs: parameter of type double bugged #264
- Joiner Bug: wrapped Joiner reloading error
-  Editor Bug: General Information - "Is Reference" not working #260
- Component bug: cropped Joiner View #257
- Component bug: Model re-selection after saving as default #256
- Component Bug: Execution fails (unrecognizedPropertyException) #245
- Joiner Bug: loading view from saved workflow fails #234
- writer bug: file extentions in combined model wrong #230
- bug: simulation files end up in fskx root folder #223
- Create error message when visualization script fails #222
- Editor Bug: Serialization of org.threeten.bp.LocalDate #215
- possible Joiner visual bug: wrong parameter in join command #214 
- Joiner Bug: Parameter suffixes are in wrong order #205
- Joiner Bug: incorrect suffix index of combined submodels #204
- Editor bug: combined model outport broken #200
- Editor deletes simulations of read-in fskx file #183
- Generated resource files for python model not written in fskx file #149
- Esti Simulator 4: parameter Description field is not long enough #488
- Esti Editor 18: Parameter Tooltip should also say that constant parameters require value #487
- Esti Editor 16: Parameter id's are not validated #485
- Esti Editor 12 & 13: rename labels #484
- Esti Editor 8: expand size of text box for long text #481
- README tab in editor Bug #387
- Joiner: second model name not assigned #369
- Simulation Configurator JS: details of parameters incorrect #368 
- Editor JS: parameter references are not implemented correctly #367
- Editor JS: "+" button locks view #366
- Editor JS: "+" button not working #365
- Editor JS: mandatory fields are not enforced #360
- Editor JS: quotation marks in model equation class
- Editor JS: some fields are not self-explanatory #352
- Editor JS: drop down menu overlaps captions #349 
- Esther Joiner 18: Update KNIME description of joiner node #480
- Esther Joiner 13: rename modelA to model1 in the metadata #478
- Esther Joiner 11: joining R and Python models fails #477
- Esther Joiner 3: source port and target port should be labels instead of inputs #473
- Esther Joiner 1: Joiner doesn't work if no Joining took place #472
- Esther Editor 20: some views are too large to fit the screen (responsive webdesign) #462
- Esther Editor 19: validate email adress #461
- Esther Editor 17: long tables need a side scroll bar #460
- Esther Editor 14: redesign simple table so it matches advanced table #458
- Esther: SimConf(3): removing simulation to default breaks port object #446 
- Joiner: second model name not assigned #369 
- Editor JS: parameter references are not implemented correctly #367 
- Editor JS: quotation marks in model equation class #354 
- Editor JS: some fields are not self-explanatory #352
- Editor JS: resizing window can misplace objects #351
- Editor JS: drop down menu overlaps captions 
- Editor JS: model type in view and settings not in sync 
- Fix faulty reading of join commands in SBML https://github.com/SiLeBAT/FSK-Lab/commit/b8b109433187ef5746207db310c4516946116db8
- Initialize model metadata and type when not set in editor (before dlg) https://github.com/SiLeBAT/FSK-Lab/commit/d8519785321db9f903475ca2d8cbd5af4c1ba50c
- Bugfix editor: change order of generation of the simulation https://github.com/SiLeBAT/FSK-Lab/commit/b101c1bcee9ae8e332ea24c5f50987ed91deb978
- Bugfix: Rename parameter classifications to match 1.0.4 types https://github.com/SiLeBAT/FSK-Lab/commit/6704abc408b812900547b84288769efd99422362
- Fix #452 Tooltip of General information -> Rights https://github.com/SiLeBAT/FSK-Lab/commit/28002b49d6d0a146063704d317a140dead86c8e4
- fixed #461: validate email adress https://github.com/SiLeBAT/FSK-Lab/commit/72205d2bf7ec40611a44112dede1498466e34887
- fixed vocabulary string for modelSubClass related to FSK-Service https://github.com/SiLeBAT/FSK-Lab/commit/09b078d95ae0d6e103dc760eee5eb1cc94361a85
- fixed #473: source and target port in Joiner are now readonly https://github.com/SiLeBAT/FSK-Lab/commit/f2118559dfe6548f0fb57950e8630de9b5fe3124
- Fix tooltips of general information creation and modification dates #450 and #451
- Added checks to LibRegistry to make installing R packages more robust https://github.com/SiLeBAT/FSK-Lab/commit/652d9ecf550d7d3b14b545ed31b124b0c9c18bc9
- Rename labels in editor node #484 
- Fix most issues in FskService. Unblock DB and use random port. https://github.com/SiLeBAT/FSK-Lab/commit/b8994c56ce769089ec6a70cf2dadcb98c0329020
- #635 fix for language_written_in https://github.com/SiLeBAT/FSK-Lab/commit/1fbb4abb79409fe26fbefd9265e5f6d016c30710
- default constructor sends null to other constructor https://github.com/SiLeBAT/FSK-Lab/commit/b05c319f17d0c3395dc1af283190703b828a4856
- Fix package installation on Linux (#639)
- #121: fixed Reader nodes throwing error on file not found
- #120: fixed Writer nodes throwing error on file not found
- Fix packages installation on Mac (#674)
- R workspace not available after reading FSKX file https://github.com/SiLeBAT/FSK-Lab/commit/73135d33d84176dcef8b208354b4980cb46cf0cb

**Comment by schuelet** [comment]
@miguelalba here as a md file:
[changelog.md](https://github.com/SiLeBAT/FSK-Lab/files/6385328/changelog.md)

**Comment by miguelalba** [comment]
https://github.com/SiLeBAT/FSK-Lab/pull/878

**Comment by llavall** [comment]
@miguelalba the changelog still hasn't changed? Do we need to wait for the next build to see something?

This is the link we provide to the user: https://github.com/SiLeBAT/FSK-Lab/blob/master/features/de.bund.bfr.knime.fsklab.feature/CHANGELOG.md
